export {default as Login} from "./Login"
export {default as Logout} from "./Logout" 
export {default as PersonalDetails } from "./PersonalDetails"
export {default as AdditionalDetails } from "./AdditionalDetails"
export {default as Dashboard } from "./Dashboard"
export {default as Profile } from "./Profile"
export {default as ProgressReport} from "./ProgressReport"
export {default as Assignment } from "./Assignment"
export {default as Notification } from "./Notification"

export {default as Payments } from "./Payments"